#' Enable the user to estimate the optimal number of basis functions.
#'
#' @name analyzeBasisFunctions
#' @author Jack R. Leary
#' @description Given a \code{Seurat} or \code{SpatialExperiment} object, generate a variety of statistics & plots that will help you to choose the optimal number of basis functions \emph{k} for usage in \code{\link{findSpatiallyVariableFeaturesBayes}}.
#' @param sp.obj An object of class \code{Seurat} or \code{SpatialExperiment} containing spatial data. Defaults to NULL.
#' @param naive.hvgs A vector containing genes that have been classified as naive HVGs from which SVGs will be detected. Defaults to NULL. 
#' @param lscale.estimator A string specifying how the global length-scale should be estimated. Must be one of "kmeans" or "variogram". Defaults to "kmeans".
#' @param n.basis.fns An integer specifying the number of basis functions to be used when approximating the GP as a Hilbert space. Defaults to 20.
#' @param kernel A string specifying the covariance kernel to be used when fitting the GP. Must be one of "exp_quad", "matern", or "periodic". Defaults to "exp_quad".
#' @param kernel.smoothness A double specifying the smoothness parameter \eqn{\nu} used when computing the Matern kernel. Must be one of 0.5, 1.5, or 2.5. Using 0.5 corresponds to the exponential kernel. Defaults to 1.5.
#' @param kernel.period An integer specifying the period parameter \eqn{p} used when computing the periodic kernel. Defaults to 100.
#' @param facet.ncol An integer specifying the number of columns in faceted plots generated with \code{\link[ggplot2]{facet_wrap}}. Defaults to NULL.
#' @param pt.size A double specifying the size of the points in scatterplots generated with \code{\link[ggplot2]{geom_point}}. Defaults to 1.
#' @param n.cores An integer specifying the number of threads used when estimating the length-scale via the variogram method. Defaults to 2.
#' @param random.seed A double specifying the random seed to be set prior to running \emph{k}-means. Defaults to 312.
#' @details
#' \itemize{
#' \item This function replicates the logic & methods used within \code{\link{findSpatiallyVariableFeaturesBayes}} to generate the basis function matrices \eqn{\phi} (non-orthonormal) and \eqn{\tilde{\phi}} (orthonormal). 
#' \item The first three elements of the returned list are visualizations of the structure of the basis functions: spatial scatterplots colored by \emph{k}-means cluster ID, basis function values, and basis function magnitudes, respectively. 
#' \item The fourth element of the returned list is a visualization of basis function eigenvalue decay. The x-axis is simply the index of the basis functions from \eqn{j = 1, \dots, k}, while the y-axis is the log of the eigenvalues \eqn{\lambda_j} of \eqn{\phi\phi^\top}. Swift eigenvalue decay indicates that the effective dimension of the spatial process is small.  
#' \item The next three elements of the returned list are \eqn{\phi} (the non-orthonormal basis function matrix), \eqn{\tilde{\phi}} (the QR-decomposed basis function matrix), and the output generated by running \code{\link[stats]{kmeans}} on the scaled spatial coordinates. 
#' \item The returned list also include an estimate of the Frobenius error of the low-rank approximation of the spatial covariance matrix \eqn{\hat{K} = \tilde{\phi}^\top \tilde{\phi}} when compared to the full spatial covariance matrix \eqn{K}. The Frobenius error is computed as: \eqn{\text{err} = \frac{||K - \hat{K}||_F}{||K||_F}}. 
#' \item The final item in the returned list is a sub-list containing all the relevant parameters used in the generation of the basis functions. This can be useful when running large experiments with many repetitions of the kernel selection procedure.
#' }
#' @import magrittr
#' @importFrom cli cli_abort
#' @importFrom parallelly availableCores
#' @importFrom Seurat GetAssayData DefaultAssay GetTissueCoordinates
#' @importFrom SingleCellExperiment logcounts
#' @importFrom dplyr select mutate across bind_cols arrange
#' @importFrom tidyr pivot_longer 
#' @importFrom SpatialExperiment spatialCoords
#' @importFrom stats kmeans median var
#' @importFrom fields rdist
#' @importFrom withr with_output_sink
#' @importFrom utils txtProgressBar setTxtProgressBar
#' @importFrom parallel makeCluster stopCluster
#' @importFrom doSNOW registerDoSNOW
#' @importFrom sp SpatialPointsDataFrame
#' @importFrom gstat variogram vgm fit.variogram
#' @importFrom ggplot2 ggplot aes geom_point scale_y_reverse labs scale_color_manual facet_wrap label_parsed labs theme element_rect scale_color_gradientn geom_line scale_x_discrete element_text
#' @return A named list containing plots and summary statistics concerning the structure & quality of the generated basis functions.
#' @seealso \code{\link{plotBasisFunctions}}
#' @seealso \code{\link{findSpatiallyVariableFeaturesBayes}}
#' @export
#' @examples
#' data(seu_brain)
#' seu_brain <- Seurat::NormalizeData(seu_brain, verbose = FALSE)
#' naive_hvgs <- getNaiveHVGs(seu_brain, n.hvg = 500L)
#' analyzeBasisFunctions(seu_brain, naive.hvgs = naive_hvgs)

analyzeBasisFunctions <- function(sp.obj = NULL, 
                                  naive.hvgs = NULL, 
                                  lscale.estimator = "kmeans", 
                                  n.basis.fns = 20L, 
                                  kernel = "exp_quad", 
                                  kernel.smoothness = 1.5, 
                                  kernel.period = 100, 
                                  facet.ncol = NULL, 
                                  pt.size = 1, 
                                  n.cores = 2L, 
                                  random.seed = 312) {
  # check inputs
  if (is.null(sp.obj)) { cli::cli_abort("Please provide a spatial data object to analyzeBasisFunctions().") }
  if (!(inherits(sp.obj, "Seurat") || inherits(sp.obj, "SpatialExperiment"))) { cli::cli_abort("Please provide an object of class {.pkg Seurat} or {.pkg SpatialExperiment}.") }
  if (is.null(naive.hvgs)) { cli::cli_abort("Please identify a set of naive HVGs prior to running analyzeBasisFunctions().") }
  kernel <- tolower(kernel)
  if (!kernel %in% c("exp_quad", "matern", "periodic")) { cli::cli_abort("Please provide a valid covariance kernel.") }
  if (kernel == "matern" && !kernel.smoothness %in% c(0.5, 1.5, 2.5)) { cli::cli_abort("When utilizing the Matern kernel you must provide a valid smoothness parameter value.") }
  if (n.cores > unname(parallelly::availableCores())) { cli::cli_abort("The number of requested cores is greater than the number of available cores.") }
  # prepare spatial coordinates data 
  if (inherits(sp.obj, "Seurat")) {
    spatial_df <- dplyr::select(Seurat::GetTissueCoordinates(sp.obj), 1:2)
  } else {
    spatial_df <- as.data.frame(SpatialExperiment::spatialCoords(sp.obj)) %>% 
                  dplyr::select(1:2)
  }
  colnames(spatial_df) <- c("x", "y")
  spatial_mtx <- scale(as.matrix(spatial_df))
  # estimate global length-scale using desired method (k-means or empirical variogram)
  set.seed(random.seed)
  kmeans_res <- stats::kmeans(spatial_mtx,
                              centers = n.basis.fns,
                              iter.max = 100L, 
                              nstart = 10L)
  kmeans_centers <- kmeans_res$centers
  if (lscale.estimator == "kmeans") {
    dists_centers <- fields::rdist(kmeans_centers, compact = TRUE)
    lscale <- stats::median(dists_centers)
  } else if (lscale.estimator == "variogram") {
    if (inherits(sp.obj, "Seurat")) {
      expr_mtx <- Seurat::GetAssayData(sp.obj,
                                       assay = Seurat::DefaultAssay(sp.obj),
                                       layer = "data")
    } else {
      expr_mtx <- SingleCellExperiment::logcounts(sp.obj)
    }
    expr_mtx <- expr_mtx[naive.hvgs, ]
    spatial_df <- dplyr::mutate(spatial_df,
                                x = as.numeric(scale(x)),
                                y = as.numeric(scale(y)))
    if (verbose) {
      withr::with_output_sink(tempfile(), {
        pb <- utils::txtProgressBar(0, length(naive.hvgs), style = 3)
      })
      progress_fun <- function(n) utils::setTxtProgressBar(pb, n)
      snow_opts <- list(progress = progress_fun)
    } else {
      snow_opts <- list()
    }
    if (n.cores > 1L) {
      cl <- parallel::makeCluster(n.cores)
      doSNOW::registerDoSNOW(cl)
    } else {
      cl <- foreach::registerDoSEQ()
    }
    vario_ranges <- foreach::foreach(g = seq_along(naive.hvgs),
                                     .combine = c,
                                     .multicombine = ifelse(length(naive.hvgs) > 1, TRUE, FALSE),
                                     .maxcombine = ifelse(length(naive.hvgs) > 1, length(naive.hvgs), 2),
                                     .inorder = TRUE,
                                     .verbose = FALSE,
                                     .packages = c("sp", "gstat", "stats"), 
                                     .options.snow = snow_opts) %dopar% {
      gene_expr <- unname(expr_mtx[naive.hvgs[g], ])
      sp_df <- sp::SpatialPointsDataFrame(spatial_df, data = data.frame(z = gene_expr))
      emp_vario <- gstat::variogram(z ~ 1, data = sp_df)
      gene_var <- stats::var(gene_expr)
      init_model <- gstat::vgm(gene_var * 0.8,
                               model = "Mat",
                               range = stats::median(emp_vario$dist, na.rm = TRUE),
                               nugget = gene_var * 0.2,
                               kappa = kernel.smoothness)
      vario_fit <- try({
        gstat::fit.variogram(emp_vario, model = init_model)
      }, silent = TRUE)
      if (inherits(vario_fit, "try-error")) {
        res <- NA_real_
      } else {
        res <- as.numeric(vario_fit[vario_fit$model == "Mat", "range"])
      }
      res
    }
    if (n.cores > 1L) {
      parallel::stopCluster(cl)
    }
    lscale <- stats::median(vario_ranges, na.rm = TRUE)
  }
  # estimate & QR-decomposed basis function matrix with user-specified kernel 
  M <- nrow(spatial_mtx)
  phi_raw <- matrix(0, 
                    nrow = M, 
                    ncol = n.basis.fns)
  for (i in seq(n.basis.fns)) {
    dist_vec <- rowSums((spatial_mtx - matrix(kmeans_centers[i, ], nrow = M, ncol = 2, byrow = TRUE))^2)
    if (kernel == "exp_quad") {
      phi_raw[, i] <- expQuadKernel(dist_vec, length.scale = lscale)
    } else if (kernel == "matern") {
      phi_raw[, i] <- maternKernel(dist_vec,
                                   length.scale = lscale,
                                   nu = kernel.smoothness)
    } else if (kernel == "periodic") {
      phi_raw[, i] <- periodicKernel(dist_vec,
                                     length.scale = lscale,
                                     period = kernel.period)
    }
  }
  phi <- try({
    qr.Q(qr(phi_raw, LAPACK = TRUE))
  }, silent = TRUE)
  if (inherits(phi, "try-error")) {
    phi <- qr.Q(qr(phi_raw))
  }
  # format basis function matrix for visualization later on
  phi_df <- as.data.frame(phi) %>% 
            magrittr::set_colnames(paste0("Phi_", seq(ncol(.))))
  phi_df_long <- bind_cols(spatial_df, phi_df) %>% 
                 dplyr::mutate(dplyr::across(c(x, y), \(z) as.numeric(scale(z)))) %>% 
                 tidyr::pivot_longer(cols = !c(x, y), 
                                     names_to = "basis", 
                                     values_to = "value") %>% 
                 dplyr::mutate(basis_label = gsub("Phi_", "", basis), 
                               basis_label = paste0("italic(j) == ", basis_label)) %>% 
                 dplyr::mutate(basis = factor(basis, levels = paste0("Phi_", seq(n.basis.fns)))) %>% 
                 dplyr::arrange(basis) %>% 
                 dplyr::mutate(basis_label = factor(basis_label, levels = unique(basis_label)))
  phi_eigen <- eigen(crossprod(phi_raw), symmetric = TRUE)
  # compute full spatial covariance matrix & compare with low-rank basis function approximation
  spatial_dist_mtx <- as.matrix(fields::rdist(spatial_mtx))
  K <- matrix(0, 
              nrow = M, 
              ncol = M)
  for (i in seq(M)) {
    dist_vec <- spatial_dist_mtx[i, ]
    if (kernel == "exp_quad") {
      K[, i] <- expQuadKernel(dist_vec, length.scale = lscale)
    } else if (kernel == "matern") {
      K[, i] <- maternKernel(dist_vec,
                             length.scale = lscale,
                             nu = kernel.smoothness)
    } else if (kernel == "periodic") {
      K[, i] <- periodicKernel(dist_vec,
                               length.scale = lscale,
                               period = kernel.period)
    }
  }
  W <- crossprod(phi, K) %*% phi
  K_hat <- phi %*% W %*% t(phi)
  frob_error <- norm(K - K_hat, type = "F") / norm(K, type = "F")
  # generate basis function plots
  p0 <- dplyr::mutate(spatial_df, kmeans_cluster = as.factor(kmeans_res$cluster)) %>% 
        ggplot2::ggplot(ggplot2::aes(x = y, y = x, color = kmeans_cluster)) + 
        ggplot2::geom_point(size = pt.size) + 
        ggplot2::scale_y_reverse() + 
        ggplot2::scale_color_manual(values = palette_cluster) + 
        ggplot2::labs(x = "Spatial 1", 
                      y = "Spatial 2", 
                      color = expression(paste(italic(k), "-means ID"))) + 
        theme_bayesVG(spatial = TRUE)
  p1 <- ggplot2::ggplot(phi_df_long, ggplot2::aes(x = y, y = x, color = value)) + 
        ggplot2::facet_wrap(~basis_label, 
                            ncol = facet.ncol, 
                            labeller = ggplot2::label_parsed) + 
        ggplot2::geom_point(size = pt.size) + 
        ggplot2::scale_y_reverse() + 
        ggplot2::scale_color_gradientn(colors = palette_heatmap) + 
        ggplot2::labs(x = "Spatial 1", 
                      y = "Spatial 2", 
                      color = expression(phi[italic(j)](italic(s)[italic(i)]))) + 
        theme_bayesVG(spatial = TRUE) + 
        ggplot2::theme(strip.clip = "on", 
                       strip.background = ggplot2::element_rect(linewidth = 2 * theme_bayesVG()$line$linewidth))
  p2 <- ggplot2::ggplot(phi_df_long, ggplot2::aes(x = y, y = x, color = abs(value))) + 
        ggplot2::facet_wrap(~basis_label, 
                            ncol = facet.ncol, 
                            labeller = ggplot2::label_parsed) + 
        ggplot2::geom_point(size = pt.size) + 
        ggplot2::scale_y_reverse() + 
        ggplot2::scale_color_gradientn(colors = palette_heatmap) + 
        ggplot2::labs(x = "Spatial 1", 
                      y = "Spatial 2", 
                      color = expression(abs~phi[italic(j)](italic(s)[italic(i)]))) + 
        theme_bayesVG(spatial = TRUE) + 
        ggplot2::theme(strip.clip = "on", 
                       strip.background = ggplot2::element_rect(linewidth = 2 * theme_bayesVG()$line$linewidth))
  p3 <- data.frame(index = factor(as.integer(seq(phi_eigen$values))), eigenvalue = phi_eigen$values) %>% 
        ggplot2::ggplot(ggplot2::aes(x = index, y = log(eigenvalue))) + 
        ggplot2::geom_point(size = 4, 
                            stroke = 0, 
                            color = "sienna") + 
        ggplot2::geom_line(ggplot2::aes(group = 1), 
                           color = "sienna", 
                           linewidth = 1) + 
        ggplot2::scale_x_discrete(labels = \(x) parse(text = paste0("italic(j) == ", x))) + 
        ggplot2::labs(x = "Basis Function", y = expression(paste(log~lambda[italic(j)]))) + 
        theme_bayesVG() + 
        ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, 
                                                           vjust = 1,
                                                           hjust = 1))
  # format results 
  formatted_kernel <- ifelse(kernel == "exp_quad", "Exponentiated Quadratic", 
                             ifelse(kernel == "matern", "Matern", "Periodic"))
  basis_params <- list(n_g = length(naive.hvgs), 
                       n_s = nrow(spatial_mtx), 
                       lengthscale_method = lscale.estimator, 
                       lengthscale_estimate = lscale, 
                       k = n.basis.fns, 
                       kernel_type = formatted_kernel, 
                       random_seed = random.seed)
  if (kernel == "matern") {
    basis_params$kernel_nu <- kernel.smoothness
  }
  if (kernel == "periodic") {
    basis_params$kernel_p <- kernel.period
  }
  res <- list(kmeans_plot = p0, 
              basis_spatial = p1, 
              basis_magnitude_spatial = p2, 
              basis_eigenvalues = p3, 
              phi_raw = phi_raw, 
              phi = phi, 
              kmeans_res = kmeans_res, 
              frobenius_error = frob_error, 
              parameters = basis_params)
  return(res)
}
