#' Compute the naive mean, variance, and dispersion of gene expression.
#'
#' @name computeNaiveGeneStatistics
#' @author Jack R. Leary
#' @description Useful as a comparison to the results generated by our Bayesian models, this function computes the naive mean, variance, and dispersion of gene expression.
#' @param sc.obj An object of class \code{Seurat} or \code{SingleCellExperiment}. Defaults to NULL.
#' @param use.norm A Boolean specifying whether the normalized counts should be used instead of raw counts. Defaults to FALSE.
#' @import magrittr
#' @importFrom SingleCellExperiment logcounts
#' @importFrom BiocGenerics counts
#' @importFrom Seurat GetAssayData DefaultAssay
#' @importFrom sparseMatrixStats rowMeans2 rowVars
#' @return A \code{data.frame} containing the per-gene naive mean, variance, and dispersion.
#' @export

computeNaiveGeneStatistics <- function(sc.obj = NULL, use.norm = FALSE) {
  # check inputs
  if (is.null(sc.obj)) { stop("Please provide all inputs to computeNaiveGeneStatistics().") }
  # extract (sparse) counts or logged counts matrix
  if (inherits(sc.obj, "SingleCellExperiment")) {
    if (use.norm) {
      expr_mat <- SingleCellExperiment::logcounts(sc.obj)
    } else {
      expr_mat <- BiocGenerics::counts(sc.obj)
    }
  } else if (inherits(sc.obj, "Seurat")) {
    expr_mat <- Seurat::GetAssayData(sc.obj,
                                     layer = ifelse(use.norm, "data", "counts"),
                                     assay = Seurat::DefaultAssay(sc.obj))
  }
  if (!inherits(expr_mat, "dgCMatrix")) {
    expr_mat <- as(expr_mat, "dgCMatrix")
  }
  # compute per-gene means
  gene_mu <- unname(sparseMatrixStats::rowMeans2(expr_mat))
  # compute per-gene variances
  gene_sigma2 <- unname(sparseMatrixStats::rowVars(expr_mat))
  # compute per-gene dispersions
  gene_dispersion <- gene_sigma2 / gene_mu
  # collate results
  gene_summary <- data.frame(gene = rownames(expr_mat),
                             mu_naive = gene_mu,
                             sigma2_naive = gene_sigma2,
                             dispersion_naive = gene_dispersion) %>%
                  magrittr::set_rownames(.$gene)
  return(gene_summary)
}
