#' Generate a plot of estimated basis functions.
#'
#' @name plotBasisFunctions
#' @author Jack R. Leary
#' @description Given a \code{Seurat} or \code{SpatialExperiment} object, generate a variety of plots showing the structure of the estimated basis functions used to approximate the GP.
#' @param sp.obj An object of class \code{Seurat} or \code{SpatialExperiment} as returned after running \code{\link{findSpatiallyVariableFeaturesBayes}}. Defaults to NULL.
#' @param plot.type A character specifying which type of plot should be generated. Must be one of "clustering", "basis_spatial", "basis_abs_spatial", or "basis_orthog". Defaults to "basis_spatial".
#' @param facet.ncol An integer specifying the number of columns in the faceted plot generated by \code{\link[ggplot2]{facet_wrap}} when \code{plot.type} is "basis_spatial" or "basis_abs_spatial". Defaults to NULL.
#' @param pt.size A double specifying the size of the points to be plotted when \code{plot.type} is "clustering", "basis_spatial", or "basis_abs_spatial". Defaults to 1.
#' @param color.palette A vector containing colors that are passed to \code{\link[ggplot2]{scale_color_gradientn}}, \code{\link[ggplot2]{scale_color_manual}}, or \code{\link[ggplot2]{scale_fill_gradientn}}, depending on the value of \code{plot.type}. Defaults to NULL.
#' @import magrittr
#' @importFrom cli cli_abort
#' @importFrom Seurat DefaultAssay GetTissueCoordinates
#' @importFrom dplyr select mutate across bind_cols arrange
#' @importFrom tidyr pivot_longer 
#' @importFrom SpatialExperiment spatialCoords
#' @importFrom coop scaler
#' @importFrom ggplot2 ggplot aes geom_point scale_y_reverse labs scale_color_gradientn scale_color_manual scale_fill_gradientn facet_wrap theme element_rect label_parsed element_text geom_tile scale_x_discrete scale_y_discrete
#' @return An object of class \code{ggplot2}.
#' @seealso \code{\link{plotModuleScores}}
#' @seealso \code{\link{plotSpatialExpression}}
#' @seealso \code{\link{plotSpatialAttributes}}
#' @export
#' @examples
#' data(seu_brain)
#' seu_brain <- Seurat::NormalizeData(seu_brain, verbose = FALSE)
#' naive_hvgs <- getNaiveHVGs(seu_brain, n.hvg = 500L)
#' seu_brain <- findSpatiallyVariableFeaturesBayes(seu_brain,
#'                                                 naive.hvgs = naive_hvgs,
#'                                                 kernel = "matern",
#'                                                 kernel.smoothness = 1.5,
#'                                                 algorithm = "meanfield",
#'                                                 n.cores = 1L,
#'                                                 save.model = TRUE, 
#'                                                 save.basis.fns = TRUE) %>%
#'              classifySVGs(n.SVG = 100L)
#' plotBasisFunctions(seu_brain, plot.type = "basis_spatial")

plotBasisFunctions <- function(sp.obj = NULL, 
                               plot.type = "basis_spatial", 
                               facet.ncol = NULL, 
                               pt.size = 1, 
                               color.palette = NULL) {
  # check inputs
  if (is.null(sp.obj)) { cli::cli_abort("Please provide all necessary inputs to plotBasisFunctions().") }
  if (!(inherits(sp.obj, "Seurat") || inherits(sp.obj, "SpatialExperiment"))) { cli::cli_abort("Please provide an object of class {.pkg Seurat} or {.pkg SpatialExperiment}.") }
  if (inherits(sp.obj, "Seurat")) {
    phi <- sp.obj@assays[[Seurat::DefaultAssay(sp.obj)]]@misc$phi
    kmeans_res <- sp.obj@assays[[Seurat::DefaultAssay(sp.obj)]]@misc$kmeans
  } else if (inherits(sp.obj, "SpatialExperiment")) {
    phi <- sp.obj@metadata$phi
    kmeans_res <- sp.obj@metadata$kmeans
  }
  if (is.null(phi) || is.null(kmeans_res)) { cli::cli_abort("The k-means results and / or basis function matrix are missing from the unstructured metadata of {.field sp.obj}.") }
  # extract & format spatial coordinates 
  if (plot.type %in% c("clustering", "basis_spatial", "basis_abs_spatial", "basis_orthogonal")) {
    if (inherits(sp.obj, "Seurat")) {
      coord_df <- Seurat::GetTissueCoordinates(sp.obj)
    } else if (inherits(sp.obj, "SpatialExperiment")) {
      coord_df <- as.data.frame(SpatialExperiment::spatialCoords(sp.obj))
    }
    coord_df <- dplyr::select(coord_df, 1:2) %>%
                as.matrix() %>%
                coop::scaler() %>%
                as.data.frame() %>%
                magrittr::set_colnames(c("x", "y"))
  }
  # format dataframe of basis functions 
  phi_df <- as.data.frame(phi) %>% 
            magrittr::set_colnames(paste0("Phi_", seq(ncol(.))))
  phi_df_long <- dplyr::bind_cols(coord_df, phi_df) %>% 
                 dplyr::mutate(dplyr::across(c(x, y), \(z) as.numeric(coop::scaler(z)))) %>% 
                 tidyr::pivot_longer(cols = !c(x, y), 
                                     names_to = "basis", 
                                     values_to = "value") %>% 
                 dplyr::mutate(basis_label = gsub("Phi_", "", basis), 
                               basis_label = paste0("italic(j) == ", basis_label)) %>% 
                 dplyr::mutate(basis = factor(basis, levels = paste0("Phi_", seq(10)))) %>% 
                 dplyr::arrange(basis) %>% 
                 dplyr::mutate(basis_label = factor(basis_label, levels = unique(basis_label)))
  # generate plot 
  if (plot.type == "clustering") {
    p <- dplyr::mutate(coord_df, kmeans_cluster = as.factor(kmeans_res$cluster)) %>% 
         ggplot2::ggplot(ggplot2::aes(x = y, y = x, color = kmeans_cluster)) + 
         ggplot2::geom_point(size = pt.size) + 
         ggplot2::scale_y_reverse() + 
         ggplot2::labs(x = "Spatial 1", 
                       y = "Spatial 2", 
                       color = expression(paste(italic(k), "-means ID"))) + 
         theme_bayesVG(spatial = TRUE)
    if (is.null(color.palette)) {
      p <- p + ggplot2::scale_color_manual(values = palette_cluster)
    }
  } else if (plot.type == "basis_spatial") {
    p <- ggplot2::ggplot(phi_df_long, ggplot2::aes(x = y, y = x, color = value)) + 
         ggplot2::facet_wrap(~basis_label, 
                             ncol = facet.ncol, 
                             labeller = ggplot2::label_parsed) + 
         ggplot2::geom_point(size = pt.size) + 
         ggplot2::scale_y_reverse() + 
         ggplot2::labs(x = "Spatial 1", 
                       y = "Spatial 2", 
                       color = expression(phi[italic(j)](italic(s)[italic(i)]))) + 
         theme_bayesVG(spatial = TRUE) + 
         ggplot2::theme(strip.clip = "on", 
                        strip.background = ggplot2::element_rect(linewidth = 2 * theme_bayesVG()$line$linewidth))
    if (is.null(color.palette)) {
      p <- p + ggplot2::scale_color_gradientn(colors = palette_heatmap)
    }
  } else if (plot.type == "basis_abs_spatial") {
    p <- ggplot2::ggplot(phi_df_long, ggplot2::aes(x = y, y = x, color = abs(value))) + 
         ggplot2::facet_wrap(~basis_label, 
                             ncol = facet.ncol, 
                             labeller = ggplot2::label_parsed) + 
         ggplot2::geom_point(size = pt.size) + 
         ggplot2::scale_y_reverse() + 
         ggplot2::labs(x = "Spatial 1", 
                       y = "Spatial 2", 
                       color = expression(abs~phi[italic(j)](italic(s)[italic(i)]))) + 
         theme_bayesVG(spatial = TRUE) + 
         ggplot2::theme(strip.clip = "on", 
                        strip.background = ggplot2::element_rect(linewidth = 2 * theme_bayesVG()$line$linewidth))
    if (is.null(color.palette)) {
      p <- p + ggplot2::scale_color_gradientn(colors = palette_heatmap)
    }
  } else if (plot.type == "basis_orthogonal") {
    p <- as.data.frame(as.table(crossprod(phi))) %>% 
         dplyr::mutate(Var1 = factor(as.integer(Var1), levels = seq_len(ncol(phi))), 
                       Var2 = factor(as.integer(Var2), levels = seq_len(ncol(phi)))) %>% 
         ggplot2::ggplot(ggplot2::aes(Var1, Var2, fill = Freq)) +
         ggplot2::geom_tile() + 
         ggplot2::scale_x_discrete(labels = \(x) parse(text = paste0("italic(j) == ", x))) +
         ggplot2::scale_y_discrete(labels = \(x) parse(text = paste0("italic(j) == ", x))) + 
         ggplot2::labs(x = "Basis Function", 
                       y = "Basis Function", 
                       fill = "Inner Product") + 
         theme_bayesVG() + 
         ggplot2::theme(axis.text.x = element_text(angle = 45, 
                                                   vjust = 1, 
                                                   hjust = 1))
    if (is.null(color.palette)) {
      p <- p + ggplot2::scale_fill_gradientn(colors = palette_heatmap)
    }
  }
  return(p)
}
